### ISSUE TITLE
landscape orientation and roman numerals for fret numbers

### ISSUE THREAD

**Issue by mtherieau** [dmpayton/python-fretboard#1]
I looked to see how landscape orientation diagrams and roman numerals for fret numbers could be supported.  It wasn't clear exactly how these could/should be implemented in python-fretboard?  I couldn't tell whether they should be style options or new settings to Fretboard class?

Here is a kludgy example that accomplishes landscape and roman numerals with a pretty heavy handed mechanism: https://gist.github.com/mtherieau/85c30d764056fc8dd48c712554a5e261

**Comment by mtherieau** [comment]
would be happy to re-work the example into a PR but would need some advice about where/how to wire in these options.

**Comment by ro31337** [comment]
It would be nice to have landscape orientation, using this library to build my pentatonic scales. It's doesn't matter how exactly these options wired.

Thanks for the library though. Would donate, but there's no button :)

**Comment by ro31337** [comment]
@mtherieau is there any way to implement this functionality? I'd paypal donate $10 for a coffee to fuel development a little bit :)

**Comment by mtherieau** [comment]
@ro31337 -- did you see the gist in the original post?  It's a little rough but it manages to render landscape.

**Comment by ro31337** [comment]
@mtherieau I even use it. I just wish to have these things little bit more organized, so it's in one code base. I think it will be nice and friendly for other folks who use this amazing work!

**Comment by dmpayton** [comment]
What the hell. I had no notifications of this issue, or that there are (recent!) comments. Thanks GitHub! 😑

If anyone wanted to donate anything, I'd encourage you to donate to Root Access, a non-profit hackerspace that I founded and run. Dollars will help the hackerspace far more than they'd help me, since most of my dollars end up there anyways. ❤️

https://rootaccess.space/donate/

I'd love to have a PR for a landscape orientation. I'll look at the original gist this weekend and see if I can put something together.🤘

cc @mtherieau @ro31337
